### ISSUE TITLE
Support grpc.reflection.v1alpha.ServerReflection

### ISSUE THREAD

**Issue by sashayakovtseva** [authzed/grpcutil#62]
Hi.

I see you've explicitly removed v1alpha support in #58.
However, many third party tools (e.g. postman, k6) are still using v1alpha reflection. Essentially now anyone who depend on that tools cannot upgrade to SpiceDB v1.26.0. 

I suggest to follow https://github.com/grpc/grpc-go approach when you support both server versions for some reasonable amount of time.

**Comment by vroldanbet** [comment]
Thanks for reporting! I've opened https://github.com/authzed/grpcutil/pull/58 and https://github.com/authzed/spicedb/pull/1718
